targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "Unicode-DFS-2016", "BSD-3-Clause" ]
exceptions = []

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    { name = "bitflags", version = "1.3.2" },
    { name = "windows-sys", version = "0.48.0" },
    { name = "windows-targets", version = "0.48.5" },
    { name = "windows_x86_64_gnu", version = "0.48.5" },
    { name = "windows_x86_64_msvc", version = "0.48.5" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []
